name: Check Pull Request

on:
  pull_request:
    branches:
        - main
        - develop
        - feat/add_workflow_android_lint
    paths-ignore:
      - ".github/**"
      - README.md

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Setup JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '1.8'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Android Lint
        run: ./gradlew lint